# Generated by Django 4.1.2 on 2022-10-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandarticlemodel',
            name='file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
