# Generated by Django 4.1.2 on 2022-10-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_brandarticlemodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=250, null=True)),
                ('file', models.FileField(null=True, upload_to='documents/%Y/%m/%d/')),
            ],
        ),
    ]
