# Generated by Django 4.1.2 on 2022-10-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_articlefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/'),
        ),
    ]
